# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
